apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-pilot-mesh-{{ .Release.Namespace }}
  labels:
    app: {{ template "pilot.name" . }}
    chart: {{ template "pilot.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# revisit in TP12
- apiGroups: ["authentication.istio.io"]
  resources: ["meshpolicies"]
  verbs: ["*"]
