apiVersion: v1
kind: ServiceAccount
metadata:
  name: rls-{{ .Values.revision | default "default" }}
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: rls
    istio.io/rev: {{ .Values.revision | default "default" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
