apiVersion: v1
kind: Service
metadata:
  name: rls-{{ .Values.revision | default "default" }}
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: rls
    istio.io/rev: {{ .Values.revision | default "default" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http-port
      protocol: TCP
    - port: 8081
      targetPort: 8081
      name: grpc-port
      protocol: TCP
  selector:
    app: rls
    istio.io/rev: {{ .Values.revision | default "default" }}
