{{ if eq .Values.provider "jaeger" }}

apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: disable-mtls-jaeger-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.provider }}
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    maistra-version: 1.0.9
    release: {{ .Release.Name }}
spec:
  targets:
  - name: jaeger-collector
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-jaeger-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.provider }}
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    maistra-version: 1.0.9
    release: {{ .Release.Name }}
spec:
  host: jaeger-collector
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: disable-mtls-zipkin
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.provider }}
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    maistra-version: 1.0.9
    release: {{ .Release.Name }}
spec:
  targets:
  - name: zipkin
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-zipkin
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.provider }}
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    maistra-version: 1.0.9
    release: {{ .Release.Name }}
spec:
  host: zipkin
  trafficPolicy:
    tls:
      mode: DISABLE

{{ end }}
