{{- if and .Values.cni.enabled (has "v2.5" .Values.cni.supportedReleases) (eq .Values.cni.instanceVersion "v2.5") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    maistra-version: "2.5.0"
  name: {{ .Values.cni.defaultResourceName }}
  namespace: {{ .Release.Namespace }}
{{- end }}
