apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: prometheus
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: {{ .Release.Namespace }}
