apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: 'true'
    {{- if .Values.prometheus.service }}
    {{- range $key, $val := .Values.prometheus.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  labels:
    maistra-version: "2.3.11"
    app: prometheus
    release: {{ .Release.Name }}
spec:
  selector:
    app: prometheus
  ports:
  - name: http-prometheus
    protocol: TCP
    port: 9090
    targetPort: 3001

{{- if .Values.prometheus.service.nodePort }}
{{- if .Values.prometheus.service.nodePort.enabled }}
# Using separate ingress for nodeport, to avoid conflict with pilot e2e test configs.
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    maistra-version: "2.0.1.1"
    app: prometheus
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 3001
    nodePort: {{ .Values.prometheus.service.nodePort.port }}
    name: http-prometheus
  selector:
    app: prometheus
{{- end }}
{{- end }}
