{{ $gateway := index .Values "gateways" "istio-ingressgateway" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "istio-ingressgateway"
{{- if not $gateway.namespace }}
  namespace: {{ $gateway.namespace | default .Release.Namespace }}
{{- else }}
  namespace: {{ $gateway.namespace | default .Release.Namespace }}
{{- end }}
  labels:
    maistra-version: 2.0.0.2
    app: {{ index .Values "gateways" "istio-ingressgateway" "labels" "istio" }}
    release: {{ .Release.Name }}
  annotations:
    "maistra.io/internal": "true"
spec:
  podSelector:
    matchLabels:
      istio: ingressgateway
  ingress:
  - {}
