{{ if and (eq .Values.tracing.provider "jaeger") (eq .Values.tracing.jaeger.template "all-in-one") .Values.tracing.jaeger.install }}
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: {{ .Values.tracing.jaeger.resourceName | default "jaeger" }}
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: {{ .Values.tracing.provider }}
    release: {{ .Release.Name }}
spec:
  strategy: allInOne

  allInOne:
    {{- if and .Values.tracing.jaeger.hub .Values.tracing.jaeger.tag .Values.tracing.jaeger.allInOneImage }}
    image: {{ .Values.tracing.jaeger.hub }}/{{ .Values.tracing.jaeger.allInOneImage }}:{{ .Values.tracing.jaeger.tag }}
    {{- end }}
    options:
      log-level: debug
      query:
        base-path: /

{{- if and .Values.tracing.jaeger.hub .Values.tracing.jaeger.tag .Values.tracing.jaeger.agentImage }}
  agent:
    image: {{ .Values.tracing.jaeger.hub }}/{{ .Values.tracing.jaeger.agentImage }}:{{ .Values.tracing.jaeger.tag }}
{{- end }}

{{- if .Values.tracing.jaeger.annotations }}
  annotations:
    {{- range $key, $value := .Values.tracing.jaeger.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}

  storage:
    options:
      memory:
        {{- if .Values.tracing.jaeger.memory.max_traces }}
        max-traces: {{ .Values.tracing.jaeger.memory.max_traces }}
        {{- else }}
        max-traces: 100000
        {{- end }}

  ingress:
    enabled: {{ .Values.tracing.ingress.enabled }}
    # XXX: should this be parameterized?
    security: oauth-proxy
{{- if .Values.tracing.ingress.annotations }}
    annotations:
      {{- range $key, $value := .Values.tracing.ingress.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
{{- end }}
    openshift:
      sar: '{"namespace": "{{ .Release.Namespace }}", "resource": "pods", "verb": "get"}'
      htpasswdFile: /etc/proxy/htpasswd/auth

  volumeMounts:
  - name: secret-htpasswd
    mountPath: /etc/proxy/htpasswd
  - name: trusted-ca-bundle
    mountPath: /etc/pki/ca-trust/extracted/pem/
    readOnly: true
  volumes:
  - name: secret-htpasswd
    secret:
      secretName: htpasswd
  - name: trusted-ca-bundle
    configMap:
      defaultMode: 420
      items:
        - key: ca-bundle.crt
          path: tls-ca-bundle.pem
      name: trusted-ca-bundle
      optional: true
  resources:
{{- if .Values.tracing.jaeger.resources }}
{{ toYaml .Values.tracing.jaeger.resources | indent 4 }}
{{- else }}
{{ toYaml .Values.global.defaultResources | indent 4 }}
{{- end }}
  affinity:
  {{- include "nodeaffinity" . | indent 2 }}

{{- if .Values.tracing.tolerations }}
  tolerations:
{{ toYaml .Values.tracing.tolerations | indent 4 }}
{{- else if .Values.global.defaultTolerations }}
  tolerations:
{{ toYaml .Values.global.defaultTolerations | indent 4 }}
{{- end }}

{{ end }}
