{{- if (eq .Values.tracing.provider "jaeger") }}
# This is to support routes on ocp 3.11 installs
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-jaeger-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: {{ .Values.tracing.provider }}
    release: {{ .Release.Name }}
  annotations:
    "maistra.io/internal": "true"
spec:
  podSelector:
    matchExpressions:
    # the value of this label depends on the deployment strategy used
    - key: app.kubernetes.io/component
      operator: In
      values:
      - all-in-one
      - query
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.tracing.jaeger.resourceName | default "jaeger" }}
      app.kubernetes.io/part-of: jaeger
      app.kubernetes.io/managed-by: jaeger-operator
  ingress:
  - ports:
    port: 8443

{{- end }}
