{{ if and (eq .Values.tracing.provider "jaeger") (eq (.Values.tracing.jaeger.agentStrategy | default "" | lower) "daemonset") .Values.tracing.jaeger.install }}
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: jaeger-agent
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: istio-jaeger
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{ end }}
