apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-sidecar-injector-admin-role-binding-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "sidecar-injector.name" . }}
    chart: {{ template "sidecar-injector.chart" . }}
    heritage: {{ .Release.Service }}
    maistra-version: 1.0.7
    release: {{ .Release.Name }}
    istio: sidecar-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-sidecar-injector-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: istio-sidecar-injector-service-account
    namespace: {{ .Release.Namespace }}
