{{ $gateway := index .Values "gateways" "istio-egressgateway" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $gateway.name }}-sds
  namespace: {{ $gateway.namespace | default .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    release: {{ .Release.Name }}
    istio.io/rev: {{ .Values.revision | default "default" }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
