{{- if .Values.grafana.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: grafana-ports-mtls-disabled
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: grafana
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: grafana
  mtls:
    mode: PERMISSIVE
  portLevelMtls:
    {{ .Values.grafana.service.externalPort }}:
      mode: DISABLE
{{- end }}