apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.grafana.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    maistra-version: "2.3.11"
    app: grafana
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.externalPort }}
      targetPort: 3001
      protocol: TCP
      name: {{ .Values.grafana.service.name }}
  selector:
    app: grafana
{{- if .Values.grafana.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.grafana.service.loadBalancerIP }}"
{{- end }}
  {{if .Values.grafana.service.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
    {{range $rangeList := .Values.grafana.service.loadBalancerSourceRanges}}
    - {{ $rangeList }}
    {{end}}
  {{end}}
