apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana"}}'
  labels:
    maistra-version: "2.3.11"
    app: grafana
    release: {{ .Release.Name }}
