{{ if .Values.cni.enabled }}
{{- if or (eq .Values.cni.instanceVersion "v2.0") (eq .Values.cni.instanceVersion "v2.1") (eq .Values.cni.instanceVersion "v2.2")}}
# This ConfigMap is used to configure a self-hosted Istio CNI installation.
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    maistra-version: "2.3.11"
  name: istio-cni-config
  namespace: {{ .Release.Namespace }}
data:
  # The CNI network configuration to add to the plugin chain on each node.  The special
  # values in this config will be automatically populated.
  cni_network_config_v2_0: |-
    {
      "cniVersion": "0.3.0",
      "name": "v2-0-istio-cni",
      "type": "v2-0-istio-cni",
      "log_level": "info",
      "kubernetes": {
          "kubeconfig": "__KUBECONFIG_FILEPATH__",
          "cni_bin_dir": "{{ default "/opt/cni/bin" .Values.cni.cniBinDir }}",
          "iptables_script": "v2-0-istio-iptables.sh",
          "exclude_namespaces": [ "{{ .Release.Namespace }}" ]
      }
    }
  cni_network_config_v2_1: |-
    {
      "cniVersion": "0.3.0",
      "name": "v2-1-istio-cni",
      "type": "v2-1-istio-cni",
      "log_level": "info",
      "kubernetes": {
          "kubeconfig": "__KUBECONFIG_FILEPATH__",
          "cni_bin_dir": "{{ default "/opt/cni/bin" .Values.cni.cniBinDir }}",
          "netns_setup_executable": "v2-1-istio-iptables",
          "exclude_namespaces": [ "{{ .Release.Namespace }}" ]
      }
    }
  cni_network_config_v2_2: |-
    {
      "cniVersion": "0.3.0",
      "name": "v2-2-istio-cni",
      "type": "v2-2-istio-cni",
      "log_level": {{ quote .Values.cni.logLevel }},
      "log_uds_address": "__LOG_UDS_ADDRESS__", 
      "kubernetes": {
          "kubeconfig": "__KUBECONFIG_FILEPATH__",
          "cni_bin_dir": "{{ default "/opt/cni/bin" .Values.cni.cniBinDir }}",
          "exclude_namespaces": [ "{{ .Release.Namespace }}" ]
      }
    }
{{- end }}
{{ end }}