apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mesh-user
  namespace: istio-system
rules:
  - apiGroups:
    - maistra.io
    resources:
    - servicemeshcontrolplanes
    verbs:
    - use
    resourceNames:
    - multitenant-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mesh-users
  namespace: istio-system
roleRef:
  kind: Role
  name: mesh-user
subjects:
- kind: User
  name: alice
- kind: User
  name: bob
- kind: Group
  name: istio-system-mesh-users

