# permissions for end users to edit istiohelminstalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: istiohelminstall-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sail-operator
    app.kubernetes.io/part-of: sail-operator
    app.kubernetes.io/managed-by: kustomize
  name: istiohelminstall-editor-role
rules:
- apiGroups:
  - maistra.io
  resources:
  - istiohelminstalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maistra.io
  resources:
  - istiohelminstalls/status
  verbs:
  - get
