apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicemeshcontrolplanes.maistra.io
spec:
  group: maistra.io
  names:
    kind: ServiceMeshControlPlane
    listKind: ServiceMeshControlPlaneList
    plural: servicemeshcontrolplanes
    singular: servicemeshcontrolplane
    shortNames:
    - smcp
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  additionalPrinterColumns:
  - name: Ready
    description: How many of the total number of member namespaces are
      configured
    type: string
    JSONPath: .status.annotations.readyComponentCount
  - name: Status
    description: Whether or not the control plane installation is up to date and ready
      to handle requests.
    type: string
    JSONPath: .status.conditions[?(@.type=="Reconciled")].reason
  - name: Template
    description: The configuration template to use as the base.
    type: string
    JSONPath: .status.lastAppliedConfiguration.template
  - name: Version
    description: The actual current version of the control plane installation.
    type: string
    JSONPath: .status.lastAppliedConfiguration.version
  - name: Age
    description: The age of the object
    type: date
    JSONPath: .metadata.creationTimestamp
  - name: Image hub
    description: The image hub used as the base for all component images.
    type: string
    priority: 1
    JSONPath: .status.lastAppliedConfiguration.istio.global.hub
  - name: Tag
    description: The image tag used for all component images.
    type: string
    priority: 1
    JSONPath: .status.lastAppliedConfiguration.istio.global.tag
  - name: Readiness status message
    description: A human-readable description of the control plane component
      readiness.
    type: string
    priority: 1
    JSONPath: .status.conditions[?(@.type=="Ready")].message
  - name: Reconciliation Status message
    description: The status of the reconciliation process, if the control plane is
      not up to date with the latest version this resource.
    type: string
    priority: 1
    JSONPath: .status.conditions[?(@.type=="Reconciled")].message
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicemeshmemberrolls.maistra.io
spec:
  group: maistra.io
  names:
    kind: ServiceMeshMemberRoll
    listKind: ServiceMeshMemberRollList
    plural: servicemeshmemberrolls
    singular: servicemeshmemberroll
    shortNames:
    - smmr
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  additionalPrinterColumns:
  - name: Ready
    description: How many of the total number of member namespaces are
      configured
    type: string
    JSONPath: .status.annotations.configuredMemberCount
  - name: Status
    description: Whether all member namespaces have been configured or why
      that's not the case
    type: string
    JSONPath: .status.conditions[?(@.type=="Ready")].reason
  - name: Age
    description: The age of the object
    type: date
    JSONPath: .metadata.creationTimestamp
  - name: Members
    description: Namespaces that are members of this Control Plane
    priority: 1
    type: string
    JSONPath: .spec.members
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicemeshmembers.maistra.io
spec:
  group: maistra.io
  names:
    kind: ServiceMeshMember
    listKind: ServiceMeshMemberList
    plural: servicemeshmembers
    singular: servicemeshmember
    shortNames:
    - smm
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  additionalPrinterColumns:
  - name: Control Plane
    description: The ServiceMeshControlPlane this namespace belongs to
    type: string
    JSONPath: .status.annotations.controlPlaneRef
  - name: Ready
    description: Whether or not namespace is configured as a member of the mesh.
    type: string
    JSONPath: .status.conditions[?(@.type=="Ready")].status
  - name: Age
    description: The age of the object
    type: date
    JSONPath: .metadata.creationTimestamp
---

# create role that can be used to grant users permission to create smcp and smmr resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maistra-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups: ["maistra.io"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maistra-admin
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: maistra-admin

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - namespaces
  - persistentvolumeclaims
  - pods
  - replicationcontrollers
  - secrets
  - serviceaccounts
  - services
  - events # is this needed?
  verbs:
  - '*'
- apiGroups:
  - apps
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/finalizers
  - ingresses # is this needed? should it be converted to a route?
  - ingresses/status
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - certmanager.k8s.io
  resources:
  - clusterissuers
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - '*'
- apiGroups:
  - authentication.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - security.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - jaegertracing.io
  resources:
  - jaegers
  verbs:
  - '*'
- apiGroups:
  - kiali.io
  resources:
  - kialis
  verbs:
  - '*'
- apiGroups:
  - maistra.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - authentication.maistra.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.maistra.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - '*'
# required by smmr controller
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - network.openshift.io
  resources:
  - clusternetworks
  verbs:
  - get
- apiGroups:
  - config.openshift.io
  resources:
  - networks
  verbs:
  - get
- apiGroups:
  - network.openshift.io
  resources:
  - netnamespaces
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups: 
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch

# required by cni daemonset
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use

# required by pod locality controller
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups: # might be required by citadel
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- nonResourceURLs:
  - '/metrics'
  verbs:
  - get

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-operator
  namespace: istio-operator

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: istio-operator-account-istio-operator-cluster-role-binding
subjects:
- kind: ServiceAccount
  namespace: istio-operator
  name: istio-operator
roleRef:
  kind: ClusterRole
  name: istio-operator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Service
metadata:
  name: admission-controller
  namespace: istio-operator
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 11999
  selector:
    name: istio-operator
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-operator
  namespace: istio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      labels:
        name: istio-operator
      annotations:
        olm.relatedImage.v1_0.3scale-istio-adapter: registry.redhat.io/openshift-service-mesh/3scale-istio-adapter-rhel8:1.0.0
        olm.relatedImage.v1_0.citadel: registry.redhat.io/openshift-service-mesh/citadel-rhel8:1.0.10
        olm.relatedImage.v1_0.cni: registry.redhat.io/openshift-service-mesh/istio-cni-rhel8:1.0.10
        olm.relatedImage.v1_0.galley: registry.redhat.io/openshift-service-mesh/galley-rhel8:1.0.10
        olm.relatedImage.v1_0.grafana: registry.redhat.io/openshift-service-mesh/grafana-rhel8:1.0.10
        olm.relatedImage.v1_0.mixer: registry.redhat.io/openshift-service-mesh/mixer-rhel8:1.0.10
        olm.relatedImage.v1_0.pilot: registry.redhat.io/openshift-service-mesh/pilot-rhel8:1.0.10
        olm.relatedImage.v1_0.prometheus: registry.redhat.io/openshift-service-mesh/prometheus-rhel8:1.0.10
        olm.relatedImage.v1_0.proxy-init: registry.redhat.io/openshift-service-mesh/proxy-init-rhel7:1.0.10
        olm.relatedImage.v1_0.proxyv2: registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:1.0.10
        olm.relatedImage.v1_0.sidecar-injector: registry.redhat.io/openshift-service-mesh/sidecar-injector-rhel8:1.0.10

        olm.relatedImage.v1_1.3scale-istio-adapter: registry.redhat.io/openshift-service-mesh/3scale-istio-adapter-rhel8:1.0.0
        olm.relatedImage.v1_1.citadel: registry.redhat.io/openshift-service-mesh/citadel-rhel8:1.1.1
        olm.relatedImage.v1_1.cni: registry.redhat.io/openshift-service-mesh/istio-cni-rhel8:1.1.1
        olm.relatedImage.v1_1.galley: registry.redhat.io/openshift-service-mesh/galley-rhel8:1.1.1
        olm.relatedImage.v1_1.grafana: registry.redhat.io/openshift-service-mesh/grafana-rhel8:1.1.1
        olm.relatedImage.v1_1.ior: registry.redhat.io/openshift-service-mesh/ior-rhel8:1.1.1
        olm.relatedImage.v1_1.mixer: registry.redhat.io/openshift-service-mesh/mixer-rhel8:1.1.1
        olm.relatedImage.v1_1.pilot: registry.redhat.io/openshift-service-mesh/pilot-rhel8:1.1.1
        olm.relatedImage.v1_1.prometheus: registry.redhat.io/openshift-service-mesh/prometheus-rhel8:1.1.1
        olm.relatedImage.v1_1.proxy-init: registry.redhat.io/openshift-service-mesh/proxy-init-rhel7:1.1.1
        olm.relatedImage.v1_1.proxyv2: registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:1.1.1
        olm.relatedImage.v1_1.sidecar-injector: registry.redhat.io/openshift-service-mesh/sidecar-injector-rhel8:1.1.1

        olm.relatedImage.v1_2.3scale-istio-adapter: registry.redhat.io/openshift-service-mesh/3scale-istio-adapter-rhel8:1.0.0
        olm.relatedImage.v1_2.citadel: registry.redhat.io/openshift-service-mesh/citadel-rhel8:1.2.0
        olm.relatedImage.v1_2.cni: registry.redhat.io/openshift-service-mesh/istio-cni-rhel8:1.2.0
        olm.relatedImage.v1_2.galley: registry.redhat.io/openshift-service-mesh/galley-rhel8:1.2.0
        olm.relatedImage.v1_2.grafana: registry.redhat.io/openshift-service-mesh/grafana-rhel8:1.2.0
        olm.relatedImage.v1_2.ior: registry.redhat.io/openshift-service-mesh/ior-rhel8:1.2.0
        olm.relatedImage.v1_2.mixer: registry.redhat.io/openshift-service-mesh/mixer-rhel8:1.2.0
        olm.relatedImage.v1_2.pilot: registry.redhat.io/openshift-service-mesh/pilot-rhel8:1.2.0
        olm.relatedImage.v1_2.prometheus: registry.redhat.io/openshift-service-mesh/prometheus-rhel8:1.2.0
        olm.relatedImage.v1_2.proxy-init: registry.redhat.io/openshift-service-mesh/proxy-init-rhel7:1.2.0
        olm.relatedImage.v1_2.proxyv2: registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:1.2.0
        olm.relatedImage.v1_2.sidecar-injector: registry.redhat.io/openshift-service-mesh/sidecar-injector-rhel8:1.2.0
    spec:
      serviceAccountName: istio-operator
      containers:
        - name: istio-operator
          image: registry.redhat.io/openshift-service-mesh/istio-rhel8-operator:1.1.1
          ports:
          - containerPort: 11999
            name: validation
          - containerPort: 60000
            name: metrics
          command:
          - istio-operator
          - --config
          - /etc/operator/olm/config.properties
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: istio-operator
#            - name: ISTIO_CNI_IMAGE_PULL_SECRET
#              value: name-of-secret
          volumeMounts:
          - name: operator-olm-config
            mountPath: /etc/operator/olm
            readOnly: true
      volumes:
      - name: operator-olm-config
        downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              fieldPath: metadata.annotations
            path: config.properties
