{{- if .Values.kiali.install }}
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: {{ .Values.kiali.resourceName | default "kiali" }}
  namespace: {{ .Release.Namespace }}
spec:
  version: "v1.24"
  installation_tag: "Kiali [{{ .Release.Namespace }}]"
  istio_namespace: "{{ .Release.Namespace }}"

  auth:
    strategy: "openshift"

  deployment:
{{- if and .Values.kiali.hub .Values.kiali.image }}
    image_name: "{{ .Values.kiali.hub }}/{{ .Values.kiali.image }}"
{{- end }}
    image_pull_policy: "{{ .Values.global.imagePullPolicy }}"
{{- if .Values.global.imagePullSecrets }}
    image_pull_secrets: 
{{- range .Values.global.imagePullSecrets }}
    - {{ . }}
{{- end }}
{{- end }}
{{- if .Values.kiali.ingress }}
{{- if .Values.kiali.ingress.enabled }}
    ingress_enabled: {{ .Values.kiali.ingress.enabled }}
{{- end }}
{{- end }}
    namespace: "{{ .Release.Namespace }}"
{{- if .Values.kiali.dashboard }}
{{- if .Values.kiali.dashboard.viewOnlyMode }}
    view_only_mode: {{ .Values.kiali.dashboard.viewOnlyMode }}
{{- end }}
{{- end }}

  external_services:
    istio:
      config_map_name: istio-{{ .Values.revision | default "default" }}
      url_service_version: http://istiod-{{ .Values.revision | default "default" }}.{{ .Release.Namespace }}:15014/version
    grafana:
      auth:
        type: "basic"
        use_kiali_token: false
        username: "internal"
        password: ""
      enabled: true
      in_cluster_url: "https://grafana.{{ .Release.Namespace }}.svc:3000"
{{- if .Values.kiali.dashboard }}
{{- if .Values.kiali.dashboard.grafanaURL }}
      url: "{{ .Values.kiali.dashboard.grafanaURL }}"
{{- end }}
{{- end }}
    prometheus:
      auth:
        type: "basic"
        use_kiali_token: false
        username: "internal"
        password: ""
      url: "https://prometheus.{{ .Release.Namespace }}.svc:9090"
    tracing:
      auth:
        type: "basic"
        use_kiali_token: false
        username: "internal"
        password: ""
      enabled: true
{{- if .Values.kiali.jaegerInClusterURL }}
      in_cluster_url: "{{ .Values.kiali.jaegerInClusterURL }}"
{{- else }}
      in_cluster_url: "https://{{ .Values.tracing.jaeger.resourceName | default "jaeger" }}-query.{{ .Release.Namespace }}.svc"
{{- end }}
      namespace: "{{ .Release.Namespace }}"
      service : ""
{{- if .Values.kiali.dashboard }}
{{- if .Values.kiali.dashboard.jaegerURL }}
      url: "{{ .Values.kiali.dashboard.jaegerURL }}"
{{- end }}
{{- end }}

{{- if .Values.kiali.contextPath }}
  server:
    web_root: "{{ .Values.kiali.contextPath }}"
{{- end }}
{{- end }}
