apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    maistra-version: "2.1.0"
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
  creationTimestamp: null
  name: federationstatuses.maistra.io
spec:
  group: maistra.io
  names:
    categories:
    - maistra-io
    kind: FederationStatus
    listKind: FederationStatusList
    plural: federationstatuses
    singular: federationstatus
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: FederationStatus is the Schema for reporting the status of a MeshFederation. The name of the FederationStatus will match the name of the istiod pod to which it is associated.  There will be one FederationStatus resource for each istiod pod.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec is unused
            type: object
          status:
            description: Status of the mesh federations
            properties:
              meshes:
                description: Meshes represents the status of each federated mesh.  The key represents the name of the MeshFederation resource configuring federation for with a remote mesh (as namespace/name).
                items:
                  description: FederationStatusDetails provides details about a particular federated mesh.
                  properties:
                    discovery:
                      description: Discovery provides details about the connection to the remote mesh.
                      properties:
                        remotes:
                          description: Remotes represents details related to the inbound connections remote meshes.
                          items:
                            description: DiscoveryRemoteStatus represents details related to an inbound connection from a remote mesh.
                            properties:
                              connected:
                                description: Connected identfies an active connection with the remote mesh.
                                type: boolean
                              lastConnected:
                                description: LastConnected represents the last time a connection with the remote mesh was successful.
                                format: date-time
                                type: string
                              lastDisconnect:
                                description: LastDisconnect represents the last time the connection with the remote mesh was disconnected.
                                format: date-time
                                type: string
                              lastDisconnectStatus:
                                description: LastDisconnectStatus is the status returned the last time the connection with the remote mesh was terminated.
                                type: string
                              lastEvent:
                                description: LastEvent represents the last time an event was received from the remote mesh.
                                format: date-time
                                type: string
                              lastFullSync:
                                description: LastFullSync represents the last time a full sync was performed with the remote mesh.
                                format: date-time
                                type: string
                              source:
                                description: Source represents the source of the remote watch.
                                type: string
                            required:
                            - connected
                            - source
                            type: object
                          type: array
                        watch:
                          description: Watch represents details related to the outbound connection to the remote mesh.
                          properties:
                            connected:
                              description: Connected identfies an active connection with the remote mesh.
                              type: boolean
                            lastConnected:
                              description: LastConnected represents the last time a connection with the remote mesh was successful.
                              format: date-time
                              type: string
                            lastDisconnect:
                              description: LastDisconnect represents the last time the connection with the remote mesh was disconnected.
                              format: date-time
                              type: string
                            lastDisconnectStatus:
                              description: LastDisconnectStatus is the status returned the last time the connection with the remote mesh was terminated.
                              type: string
                            lastEvent:
                              description: LastEvent represents the last time an event was received from the remote mesh.
                              format: date-time
                              type: string
                            lastFullSync:
                              description: LastFullSync represents the last time a full sync was performed with the remote mesh.
                              format: date-time
                              type: string
                          required:
                          - connected
                          type: object
                      type: object
                    exports:
                      description: Exports provides details about the services exported by this mesh.
                      items:
                        description: MeshServiceMapping represents the name mapping between an exported service and its local counterpart.
                        properties:
                          exportedName:
                            description: ExportedName represents the fully qualified domain name (FQDN) of an exported service.  For an exporting mesh, this is the name that is exported to the remote mesh. For an importing mesh, this would be the name of the service exported by the remote mesh.
                            type: string
                          localService:
                            description: LocalService represents the service in the local (i.e. this) mesh. For an exporting mesh, this would be the service being exported. For an importing mesh, this would be the imported service.
                            properties:
                              hostname:
                                description: Hostname represents fully qualified domain name (FQDN) used to access the service.
                                type: string
                              name:
                                description: Name represents the simple name of the service, e.g. the metadata.name field of a kubernetes Service.
                                type: string
                              namespace:
                                description: Namespace represents the namespace within which the service resides.
                                type: string
                            required:
                            - hostname
                            - name
                            - namespace
                            type: object
                        required:
                        - exportedName
                        - localService
                        type: object
                      type: array
                    imports:
                      description: Imports provides details about the services imported by this mesh.
                      items:
                        description: MeshServiceMapping represents the name mapping between an exported service and its local counterpart.
                        properties:
                          exportedName:
                            description: ExportedName represents the fully qualified domain name (FQDN) of an exported service.  For an exporting mesh, this is the name that is exported to the remote mesh. For an importing mesh, this would be the name of the service exported by the remote mesh.
                            type: string
                          localService:
                            description: LocalService represents the service in the local (i.e. this) mesh. For an exporting mesh, this would be the service being exported. For an importing mesh, this would be the imported service.
                            properties:
                              hostname:
                                description: Hostname represents fully qualified domain name (FQDN) used to access the service.
                                type: string
                              name:
                                description: Name represents the simple name of the service, e.g. the metadata.name field of a kubernetes Service.
                                type: string
                              namespace:
                                description: Namespace represents the namespace within which the service resides.
                                type: string
                            required:
                            - hostname
                            - name
                            - namespace
                            type: object
                        required:
                        - exportedName
                        - localService
                        type: object
                      type: array
                    mesh:
                      description: Mesh is the mesh to which this status applies.  This maps to a MeshFederation resource.
                      type: string
                  required:
                  - discovery
                  - exports
                  - imports
                  - mesh
                  type: object
                nullable: true
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []