apiVersion: v1
kind: ServiceAccount
metadata:
  name: threescale-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.5.0"
    app: 3scale-istio-adapter
    chart: {{ template "threescale.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
