apiVersion: v1
data:
  session_secret: ""
kind: Secret
metadata:
  name: prometheus-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio
    chart: {{ template "istio.chart" . }}
    heritage: {{ .Release.Service }}
    maistra-version: 1.1.16.2
    release: {{ .Release.Name }}
type: Opaque
