{{- if or .Values.tracing.enabled .Values.grafana.enabled .Values.prometheus.enabled .Values.kiali.enabled }}
apiVersion: v1
data:
  auth: ""
  rawPassword: ""
kind: Secret
metadata:
  name: htpasswd
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: istio
    release: {{ .Release.Name }}
type: Opaque
{{- end }}
