apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-ca-bundle
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: istio
    release: {{ .Release.Name }}
    config.openshift.io/inject-trusted-cabundle: "true"
