apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-to-use-prometheus
  namespace: custom-prometheus
rules:
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["prometheuses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-to-use-prometheus
  namespace: custom-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-to-use-prometheus
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: meshadmin-2
