{{ $gateway := index .Values "gateways" "istio-ingressgateway" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $gateway.name }}
{{- if not $gateway.namespace }}
  namespace: {{ $gateway.namespace | default .Release.Namespace }}
{{- else }}
  namespace: {{ $gateway.namespace | default .Release.Namespace }}
{{- end }}
  labels:
    maistra-version: "2.3.11"
{{ $gateway.labels | toYaml | indent 4 }}
    release: {{ .Release.Name }}
  annotations:
    "maistra.io/internal": "true"
spec:
  podSelector:
    matchLabels:
{{ $gateway.labels | toYaml | indent 6 }}
  ingress:
  - {}
