{{ $gateway := index .Values "gateways" "istio-ingressgateway" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $gateway.name }}-sds
  namespace: {{ $gateway.namespace | default .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    release: {{ .Release.Name }}
    istio.io/rev: {{ .Values.revision | default "default" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $gateway.name }}-sds
subjects:
- kind: ServiceAccount
  name: {{ $gateway.name }}-service-account
---
