{{ if .Values.dashboard.secretName }}
# this is like the old demo secret enabled by .Values.createDemoSecret
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dashboard.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
{{ if .Values.dashboard.user }}
  username: {{ b64enc .Values.dashboard.user }}
{{ end }}
{{ if .Values.dashboard.passphrase }}
  passphrase: {{ b64enc .Values.dashboard.passphrase }}
{{ end }}
{{ end }}
