apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.global.clusterScoped }}ClusterRoleBinding{{ else }}RoleBinding{{ end }}
metadata:
  {{ if not .Values.global.clusterScoped }}namespace: {{ .Release.Namespace }}{{ end }}
  name: istiod-clusterrole-{{ .Values.revision | default "default" }}-{{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: istiod
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istiod-clusterrole-{{ .Values.revision | default "default" }}-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: istiod-{{ .Values.revision | default "default" }}
    namespace: {{ .Release.Namespace }}
---
{{- if not (eq (toString .Values.pilot.env.PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER) "false") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.global.clusterScoped }}ClusterRoleBinding{{ else }}RoleBinding{{ end }}
metadata:
  {{ if not .Values.global.clusterScoped }}namespace: {{ .Release.Namespace }}{{ end }}
  name: istiod-gateway-controller-{{ .Values.revision | default "default" }}-{{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: istiod
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istiod-gateway-controller-{{ .Values.revision | default "default" }}-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: istiod-{{ .Values.revision | default "default" }}
  namespace: {{ .Release.Namespace }}
{{- end }}