{{- if .Values.pilot.jwksResolverExtraRootCA }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pilot-jwks-extra-cacerts-{{ .Values.revision | default "default" }}
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    release: {{ .Release.Name }}
    istio.io/rev: {{ .Values.revision | default "default" }}
data:
  extra.pem: {{ .Values.pilot.jwksResolverExtraRootCA | quote }}
{{- end }}
