# Dedicated cluster role - istiod will use fewer dangerous permissions ( secret access in particular ).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istiod-internal-{{ .Values.revision | default "default" }}-{{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: istiod
    release: {{ .Release.Name }}
rules:
  # for k8s service account token authentication
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  # for istiod to check if the proxy has permissions to read secrets
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
