apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-istiod-{{ .Values.revision | default "default" }}
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: istiod
    istio: pilot
    istio.io/rev: {{ .Values.revision | default "default" }}
    release: {{ .Release.Name }}
  annotations:
    "maistra.io/internal": "true"
spec:
  podSelector:
    matchLabels:
      app: istiod
      istio.io/rev: {{ .Values.revision | default "default" }}
  ingress:
  - ports:
    port: webhook
