apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istiod-internal-{{ .Values.revision | default "default" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "maistra.io/internal": "true"
  labels:
    maistra-version: "2.3.11"
    app: istiod
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istiod-internal-{{ .Values.revision | default "default" }}
subjects:
  - kind: ServiceAccount
    name: istiod-{{ .Values.revision | default "default" }}
    namespace: {{ .Release.Namespace }}
