{{- if .Values.ingress.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tracing
  namespace: {{ .Release.Namespace }}
  labels:
    app: tracing
    jaeger-infra: tracing-service
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  to:
    kind: Service
    name: tracing
  tls:
    termination: passthrough
{{ if eq .Values.provider "jaeger" }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jaeger-query
  namespace: {{ .Release.Namespace }}
  labels:
    app: jaeger
    jaeger-infra: query-service
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  to:
    kind: Service
    name: jaeger-query
  tls:
    termination: passthrough
{{ end }}
{{- end -}}
