{{ if eq .Values.provider "jaeger" }}

apiVersion: v1
kind: List
metadata:
  name: jaeger-services
  namespace: {{ .Release.Namespace }}
  labels:
    app: jaeger
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-query
    namespace: {{ .Release.Namespace }}
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: jaeger-query-tls
      {{- range $key, $val := .Values.service.annotations }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    labels:
      app: jaeger
      jaeger-infra: query-service
      chart: {{ template "tracing.chart" . }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  spec:
    ports:
    - name: jaeger-query
      port: 80
      protocol: TCP
      targetPort: 3001
    selector:
      app: jaeger
      jaeger-infra: query-pod
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-collector
    namespace: {{ .Release.Namespace }}
    labels:
      app: jaeger
      jaeger-infra: collector-service
      chart: {{ template "tracing.chart" . }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  spec:
    ports:
    - name: jaeger-collector-tchannel
      port: 14267
      protocol: TCP
      targetPort: 14267
    - name: jaeger-collector-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: jaeger-collector-zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
    selector:
      app: jaeger
      jaeger-infra: collector-pod
    type: ClusterIP
{{ end }}
