{{- if .Values.global.mtls.enabled }}
# These policy and destination rules effectively enable mTLS for all services in the mesh. For now,
# they are added to Istio installation yaml for backward compatible. In future, they should be in
# a separated yaml file so that customer can enable mTLS independent from installation.

# Authentication policy to enable mutual TLS for all services (that have sidecar) in the mesh.
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "default"
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: istio
    release: {{ .Release.Name }}
spec:
  mtls:
    mode: STRICT
---
# Corresponding destination rule to configure client side to use mutual TLS when talking to
# any service (host) in the mesh.
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: "default"
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: istio
    release: {{ .Release.Name }}
spec:
  host: "*.{{ .Values.global.proxy.clusterDomain }}"
  {{- if .Values.global.defaultConfigVisibilitySettings }}
  exportTo:
  - '*'
  {{- end }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
# Destination rule to disable (m)TLS when talking to API server, as API server doesn't have sidecar.
# Customer should add similar destination rules for other services that don't have sidecar.
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: "api-server"
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.3.11"
    app: istio
    release: {{ .Release.Name }}
spec:
  host: "kubernetes.default.svc.{{ .Values.global.proxy.clusterDomain }}"
  {{- if .Values.global.defaultConfigVisibilitySettings }}
  exportTo:
  - '*'
  {{- end }}
  trafficPolicy:
    tls:
      mode: DISABLE
{{- end }}
