apiVersion: v1
data:
  session_secret: ""
kind: Secret
metadata:
  name: prometheus-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.0.6.2"
    app: istio
    release: {{ .Release.Name }}
type: Opaque
