# Dedicated cluster role - istiod will use fewer dangerous permissions ( secret access in particular ).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istiod-internal-{{ .Values.revision | default "default" }}-{{ .Release.Namespace }}
  labels:
    maistra-version: "2.1.0"
    app: istiod
    release: {{ .Release.Name }}
rules:
  # for k8s service account token authentication
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
