{{- if (not .Values.global.mtls.enabled) }}
# Authentication policy to enable permissive mode for all services (that have sidecar) in the mesh.
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "default"
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: "2.0.4"
    app: istio
    release: {{ .Release.Name }}
spec:
  mtls:
    mode: PERMISSIVE
{{- end }}
