apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-mesh
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: 2.0.0
    app: istio
    release: {{ .Release.Name }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          "maistra.io/member-of": "{{ .Release.Namespace }}"

---

# this will work for all routes into the mesh namespace, but not on ocp 3.11
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-ingress-router
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: 2.0.0
    app: istio
    release: {{ .Release.Name }}
  annotations:
    "maistra.io/internal": "true"
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress

---

# this will work for all routes into the mesh namespace referencing a labelled pod, but not on ocp 3.11
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-expose-route
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: 2.0.0
    app: istio
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      maistra.io/expose-route: "true"
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress

# if users are running a custom Jaeger instance in the control plane namespace,
# we need to make sure that it's accessible through its Route
{{ if and (not .Values.tracing.enabled) (.Values.global.tracer.zipkin.address) }}
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-external-jaeger-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: 2.0.0
    app: jaeger
    release: {{ .Release.Name }}
  annotations:
    "maistra.io/internal": "true"
spec:
  podSelector:
    matchExpressions:
    # the value of this label depends on the deployment strategy used
    - key: app.kubernetes.io/component
      operator: In
      values:
      - all-in-one
      - query
    matchLabels:
      app.kubernetes.io/part-of: jaeger
      app.kubernetes.io/managed-by: jaeger-operator
  ingress:
  - ports:
    port: 8443
{{ end }}
